version: "3.8"

services:
  api:
    container_name: monion-api
    build:
      dockerfile: Dockerfile
      context: monion-api/
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - ./monion-api:/usr/src/app
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - ${PORT_API}:3000
    depends_on:
      - postgres
    networks:
      - monion-network
  postgres:
    container_name: monion-db
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - monion-network
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: monion-fe/
      target: development
    volumes:
      - ./monion-fe:/usr/src/app
    command: npm run start
    ports:
      - ${PORT_WEB}:80
    depends_on:
      - api

volumes:
  docker-nest-postgres:

networks:
  monion-network:
