name: Run Unit Tests

on:
  push:
    branches: [main]
    paths:
      - "monion-api/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - "monion-api/**"
      - ".github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd monion-api
          pnpm ci

      - name: Run tests
        run: |
          cd monion-api
          pnpm run test
