name: Code Style Checks

on:
  push:
    branches: [main]
    paths:
      - "monion-api/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - "monion-api/**"
      - ".github/workflows/**"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd monion-api
          pnpm install

      - name: Run Prettier
        run: |
          cd monion-api
          npm run format -- --check
